language: android

jdk: oraclejdk8

before_script:
  - chmod +x gradlew

 
android:
  components:
   - build-tools-20.0.0
       - android-L
       - sys-img-armeabi-v7a-android-tv-l
       - add-on
       - extra